### PR TITLE
Merged mbvt tile data source

### PR DESCRIPTION
**Pull request by farfromrefug**
As talked about. 
Let me know if you want me to do more

### CODE REVIEW

**Comment by mtehver** [comment]
I did a quick review of the code. I see one problem regarding the 'replace with parent' flag. The code currently ignores the tile with this flag set. The correct behavior is actually complex - you would need to download the parent yourself and extract the subtile from the parent by scaling/clipping coordinates.

**Comment by farfromrefug** [comment]
@mtehver Thought it was already done. How do you handle this for raster tiles?

**Comment by farfromrefug** [comment]
@mtehver  can you advise? are you not already doing this for normal data sources? 
I am seeing that you are preparing for a release. would love to see that in

**Comment by farfromrefug** [comment]
@mtehver sorry to bump this. But i am working again on Carto and this is really something i would to see working.
My implementation of this data source is Java is really slow especially at high zoom level, i would really like to see what's the result when written in C. But i am quite lost in how to handle the  'replace with parent'

**Comment by farfromrefug** [comment]
@mtehver Thanks a lot! Can't wait to test it. So right now the implementation does not handle the parent flag, right?

**Comment by mtehver** [comment]
I have changed the implementation a bit to handle it better. The correct implementation would be to decompress -> decode -> scale -> clip -> encode the tile that has 'replacewithparent' flag. This is too complex and in practice I will forward the tile with this flag set. Also, I have added optional ungzipping of the tile data. Some online sources use gzipped MBVT without HTTP headers indicating the compression method.

**Pull request merged**
