### PR TITLE
Doc refactor

### PR DESCRIPTION
**Pull request by jaakla**
Major refactoring of mobile SDK docs

### CODE REVIEW

**Comment by jaakla** [comment]
@csubira can this PR be previewed in staging somehow?

**Comment by csubira** [comment]
Hi @jaakla ! I created a branch in the documentation repository that is getting content from `doc-refactor`, you can see the staging link [here](http://mobilesdk-doc-refactor.documentation.carto-staging.com/documentation/mobile-sdk/guides/getting-started/).
Besides, if you want to edit-and-check you can use that branch to run documentation repository locally. Just ping me and I'll give you some tips to make it work!

**Comment by jaakla** [comment]
@inigomedina @csubira 
Here is reviewed content, should be quite good for now. Following things are broken still, I cannot / dont know how to fix:
* Reference doc page 01-intro.md parsing for header failed, I removed it, just does not look nice.
* Tagline in title is broken as "Mobile SDK is" - the rest is missing. Where this is defined?
* Start page /documentation/mobile-sdk/ has first section with description ok (where this can be edited?), but the other sections are from carto.js and wrong here.
* Language selection tabs not working for me - @csubira has js/css level solution for that AFAIK

**Comment by jaakla** [comment]
the docs in mobile-sdk and 'doc-rewrite' branch seems to be quite good now. 

One issue: the Overview page of Mobile SDK Guides section has missing graphics for the "Map View" part. I suggest one of two options here:
a) technical drawing in start of the "Map view" page itself. This would be much prettier with some visual design added, currently this is my best with [gdrive drawing](https://docs.google.com/drawings/d/1_X6c9iYFNd9rjIZRg7PVee12moT_-wJAEKBoP6BCmSI/edit?usp=sharing).
b) use a screenshot from mobile samples app -  this shows some features and has probably a bit nicer ready to be used image overall:
img_6881

**Pull request merged**
