### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by Nikituh**
@csobier PR so you could better review

Also, this won't go live until 4.1.0 is released, but would be nice to review it in staging

### CODE REVIEW

**Comment by jaakla** [comment]
Please put it to preview, but not live, as the SDK 4.1.0 what is base for these updates is NOT released yet.

**Comment by csobier** [comment]
@Nikituh , take a look at the copyedits I made. And most importantly, the docs/API.md file which displays the organization of files. We still need to fix any references to the file you just deprecated (offline_maps.md) and let me know where the newly added files are going - so that I can match the structure in the Docs repo.

**Comment by csobier** [comment]
@Nikituh , just applied some minor copyedits (Note when writing: always use active voice, don't use contractions, and when renaming headings- you have to manually fix all the urls to that heading- it's not a content management system that does it automatically, unfortunately :-( 

Will update Docs staging and ping you when it's refreshed!

**Comment by Nikituh** [comment]
> always use active voice, don't use contractions

We are writing for developers, not lawyers. Developers are a fun-loving bunch. Use of colloquial language is... at least sometimes acceptable :)

**Comment by jaakla** [comment]
Thanks you all! There are some minor tweaks (get started page to SDK 4.1.0 version), but SDK 4.1.0 release is done, after more than 5 month of work!

**Pull request merged**
